In [2]:
import pandas as pd
a=pd.Series(10)
print(a)

0    10
dtype: int64


In [3]:
a=pd.Series([10,20,30])
print(a)


0    10
1    20
2    30
dtype: int64


In [4]:
a=pd.Series([10,20,30],index=[1,2,3])
print(a)

1    10
2    20
3    30
dtype: int64


In [5]:
a=pd.Series([10,20,30],index=['a','b','c'])
print(a)

a    10
b    20
c    30
dtype: int64


In [7]:
import numpy as np
a=pd.Series([10,20,np.nan])
print(a)

0    10.0
1    20.0
2     NaN
dtype: float64


In [8]:
a=[10,20,30,'shameer']
print(a)
type(a)
b=pd.Series(a)
print(b)
type(b)

[10, 20, 30, 'shameer']
0         10
1         20
2         30
3    shameer
dtype: object


pandas.core.series.Series

In [10]:
a=[10,20,30,40,50,60]
df=pd.DataFrame(a)
print(df)
type(df)

    0
0  10
1  20
2  30
3  40
4  50
5  60


pandas.core.frame.DataFrame

In [11]:
a=[['shameer',99],['sameer',100],['shaik',98]]
print(a)
df=pd.DataFrame(a)
print(df)

[['shameer', 99], ['sameer', 100], ['shaik', 98]]
         0    1
0  shameer   99
1   sameer  100
2    shaik   98


In [14]:
a=[['shameer',99],['sameer',100],['shaik',98]]
print(a)
df=pd.DataFrame(a,columns=['Name','Marks'])
print(df)
print(df['Name'])
b=df['Name']
type(b)

[['shameer', 99], ['sameer', 100], ['shaik', 98]]
      Name  Marks
0  shameer     99
1   sameer    100
2    shaik     98
0    shameer
1     sameer
2      shaik
Name: Name, dtype: object


pandas.core.series.Series

In [16]:
#datesrange
d=pd.date_range('20191110',periods=10,freq='M')#use D for dates or Y for years
print(d)

DatetimeIndex(['2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29',
               '2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30',
               '2020-07-31', '2020-08-31'],
              dtype='datetime64[ns]', freq='M')


In [27]:
#to print 10 random rows with 4 columns
r=np.random.randn(10,4)
print(r)
df=pd.DataFrame(r,index=d,columns=list('ABCD'))
print(df)
df.shape
df.columns
df.info()
df.head()#prints first 5 rows
df.head(n=2)#first 2 rows
df.tail(3)#last 3 rows
df.isnull()

[[-0.96407627 -1.51532084  1.58232358 -0.99168184]
 [-1.13670226 -0.06238361 -2.02823642 -1.12629048]
 [ 0.58495614  1.29060077  1.0876952   0.81309951]
 [ 1.36270362  0.53427535 -1.03426756 -1.59724981]
 [ 0.31628279  0.55689527 -0.6609227  -0.37289685]
 [ 0.69660036 -0.97145945 -0.03565763 -0.38911629]
 [-0.77520423 -1.79732994  1.07185267  1.31221099]
 [-0.32744908 -0.17011265 -0.06277905  0.78749498]
 [ 0.5034266  -0.34202414 -0.41228666 -1.07334113]
 [-2.9146894   2.36440818 -1.97871996 -0.71822441]]
                   A         B         C         D
2019-11-30 -0.964076 -1.515321  1.582324 -0.991682
2019-12-31 -1.136702 -0.062384 -2.028236 -1.126290
2020-01-31  0.584956  1.290601  1.087695  0.813100
2020-02-29  1.362704  0.534275 -1.034268 -1.597250
2020-03-31  0.316283  0.556895 -0.660923 -0.372897
2020-04-30  0.696600 -0.971459 -0.035658 -0.389116
2020-05-31 -0.775204 -1.797330  1.071853  1.312211
2020-06-30 -0.327449 -0.170113 -0.062779  0.787495
2020-07-31  0.503427 -0.342024

A      B      C      D
2019-11-30  False  False  False  False
2019-12-31  False  False  False  False
2020-01-31  False  False  False  False
2020-02-29  False  False  False  False
2020-03-31  False  False  False  False
2020-04-30  False  False  False  False
2020-05-31  False  False  False  False
2020-06-30  False  False  False  False
2020-07-31  False  False  False  False
2020-08-31  False  False  False  False

In [32]:
r=np.random.randn(10,4)
df=pd.DataFrame(r,index=d,columns=list('ABCD'))
df.dropna(axis=1)
df['A'].value_counts()#used to count frequnecy of values
df.corr()#used to find corelations

A         B         C         D
A  1.000000 -0.253928  0.255518 -0.268016
B -0.253928  1.000000 -0.158365 -0.474357
C  0.255518 -0.158365  1.000000  0.329357
D -0.268016 -0.474357  0.329357  1.000000

In [35]:
r=np.random.randn(10,4)
df=pd.DataFrame(r,index=d,columns=list('ABCD'))
print(df)
df.describe()
#df.describe(include=['object']) for objects
#df.describe(include='all')for all columns

                   A         B         C         D
2019-11-30 -1.378824  0.014081 -0.550593  0.806361
2019-12-31  0.633731 -0.319240  0.187846 -2.062936
2020-01-31  2.304544 -0.257300 -0.017010 -1.504868
2020-02-29  0.405839 -0.720494  0.324471 -0.460957
2020-03-31  0.925637 -1.453239  0.031625 -0.160618
2020-04-30 -0.282667  0.947918  0.505685 -0.057947
2020-05-31 -0.138763  1.327259 -1.498101  0.806627
2020-06-30  0.839281 -0.095076 -0.867711 -1.558980
2020-07-31 -0.900357 -0.198621 -0.279949  0.354524
2020-08-31 -2.875501  1.712131  0.716362  0.268181


A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.046708   0.095742  -0.144738  -0.357061
std     1.433569   0.963080   0.673301   1.022846
min    -2.875501  -1.453239  -1.498101  -2.062936
25%    -0.745934  -0.303755  -0.482932  -1.243890
50%     0.133538  -0.146849   0.007308  -0.109282
75%     0.787894   0.714458   0.290315   0.332938
max     2.304544   1.712131   0.716362   0.806627